import { ExpenseCharts } from "../ExpenseCharts.jsx";
import { Badge, Button, EmptyState, Icon, PageErrorBoundary, Reveal } from "../shared.jsx";
import { useToast } from "../toast.js";
import { downloadCsv, money, shortDate, today } from "../utils.js";
import { useState } from "react";

/* Custos: gráficos + lançamentos com filtro, busca e aprovação por perfil. */
export function ExpensesPage({ expenses, budgets = [], canApprove, onStatus, onSaveBudget, role }) {
  const notify = useToast();
  const [query, setQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("Todos");
  const [categoryFilter, setCategoryFilter] = useState("Todas");
  const [monthFilter, setMonthFilter] = useState("");
  const handleStatus = (id, status, title) => {
    onStatus(id, status);
    notify({ tone: status === "Aprovada" ? "success" : "info", message: status === "Aprovada" ? `${title} liberada no orçamento.` : `${title} não seguirá para pagamento.`, title: status === "Aprovada" ? "Despesa aprovada" : "Despesa rejeitada" });
  };
  const rows = expenses.filter((expense) => (statusFilter === "Todos" || expense.status === statusFilter)
    && (categoryFilter === "Todas" || expense.category === categoryFilter)
    && (!monthFilter || String(expense.date || "").startsWith(monthFilter))
    && `${expense.id} ${expense.title} ${expense.requester} ${expense.category} ${expense.notes || ""}`.toLowerCase().includes(query.toLowerCase()));
  const month = today().slice(0, 7);
  return (
    <PageErrorBoundary>
      <ExpenseCharts budgets={budgets} expenses={expenses} onSelectCategory={(category) => { setCategoryFilter(category); if (category !== "Todas" && !monthFilter) setMonthFilter(month); setQuery(""); setStatusFilter("Todos"); }} onSelectExpense={(expense) => { setQuery(expense.title); setMonthFilter(String(expense.date || "").slice(0, 7)); setStatusFilter("Todos"); }} onSelectMonth={(selected) => { setMonthFilter(selected); setQuery(""); setStatusFilter("Todos"); }} selectedCategory={categoryFilter} selectedMonth={monthFilter} />
      <Reveal><section className="panel page-panel"><div className="panel-heading"><div><h2>Orçamentos por categoria</h2><p>Compare despesas pendentes e aprovadas com o limite mensal.</p></div></div>{canApprove && <form className="toolbar" onSubmit={onSaveBudget}><input aria-label="Categoria do orçamento" name="category" placeholder="Categoria" required /><input aria-label="Mês do orçamento" defaultValue={month} name="month" required type="month" /><input aria-label="Limite mensal" min="0.01" name="amount" placeholder="Limite (R$)" required step="0.01" type="number" /><Button type="submit"><Icon name="plus" size={14} /> Salvar orçamento</Button></form>}{budgets.length ? <div className="table-scroll"><table><thead><tr><th>Categoria</th><th>Mês</th><th>Gasto contabilizado</th><th>Limite</th><th>Uso</th></tr></thead><tbody>{budgets.map((budget) => { const spent = expenses.filter((expense) => expense.category === budget.category && String(expense.date || "").startsWith(String(budget.month).slice(0, 7)) && expense.status !== "Rejeitada").reduce((sum, expense) => sum + Number(expense.amount || 0), 0); const pct = budget.amount ? Math.min(100, Math.round(spent / budget.amount * 100)) : 0; return <tr key={budget.id}><td>{budget.category}</td><td>{String(budget.month).slice(0, 7)}</td><td>{money(spent)}</td><td>{money(budget.amount)}</td><td><span className={pct >= 90 ? "text-warning" : ""}>{pct}%</span><div className="budget-meter"><i style={{ width: `${pct}%` }} /></div></td></tr>; })}</tbody></table></div> : <p className="quiet-note">Nenhum limite mensal definido.</p>}</section></Reveal>
      <Reveal delay={0.08}><section className="panel page-panel"><div className="panel-heading"><div><h2>Lançamentos</h2><p>Os gráficos consideram despesas pendentes e aprovadas; rejeitadas ficam fora das análises de custo.</p></div>{(categoryFilter !== "Todas" || monthFilter || query) && <button className="text-link" onClick={() => { setCategoryFilter("Todas"); setMonthFilter(""); setQuery(""); setStatusFilter("Todos"); }} type="button">Limpar filtros</button>}</div><div className="toolbar"><label className="search-box"><Icon name="search" size={18} /><input aria-label="Buscar despesa" onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por descrição, categoria ou solicitante" value={query} /></label><select aria-label="Filtrar despesas por status" className="filter-select" onChange={(event) => setStatusFilter(event.target.value)} value={statusFilter}><option>Todos</option><option>Pendente</option><option>Aprovada</option><option>Rejeitada</option></select><Button onClick={() => downloadCsv(rows, "gesti-relatorio-custos", ["Código", "Descrição", "Categoria", "Solicitante", "Data", "Valor", "Status", "Justificativa"], (expense) => [expense.id, expense.title, expense.category, expense.requester, expense.date, expense.amount, expense.status, expense.notes || ""])} variant="secondary"><Icon name="download" size={15} /> CSV</Button></div>{rows.length ? <div className="table-scroll"><table><thead><tr><th>Descrição</th><th>Solicitante</th><th>Data</th><th>Valor</th><th>Status</th>{canApprove && <th>Ação</th>}</tr></thead><tbody>{rows.map((expense) => <tr key={expense.id}><td><span className="cell-title">{expense.title}</span><span className="cell-subtitle">{expense.id} · {expense.category}{expense.notes ? ` · ${expense.notes}` : ""}</span></td><td>{expense.requester}</td><td>{shortDate(expense.date)}</td><td className="amount-cell">{money(expense.amount)}</td><td><Badge tone={expense.status === "Aprovada" ? "green" : expense.status === "Rejeitada" ? "red" : "amber"}>{expense.status}</Badge></td>{canApprove && <td>{expense.status === "Pendente" ? <div className="approval-actions"><button aria-label={`Aprovar ${expense.title}`} className="approve-button" onClick={() => handleStatus(expense.id, "Aprovada", expense.title)} type="button"><Icon name="check" size={16} /></button><button aria-label={`Rejeitar ${expense.title}`} className="reject-button" onClick={() => handleStatus(expense.id, "Rejeitada", expense.title)} type="button"><Icon name="close" size={16} /></button></div> : <span className="quiet-note">Concluída</span>}</td>}</tr>)}</tbody></table></div> : <EmptyState note="Registre uma despesa ou ajuste os filtros." title="Sem lançamentos" />}</section></Reveal>
      <Reveal delay={0.05}><p className="permission-note">A aprovação está disponível para Admin, Dono da empresa e Gerência{role ? ` · você está como ${role}` : ""}.</p></Reveal>
    </PageErrorBoundary>
  );
}
